### ISSUE TITLE
url_for generates http instead of https when running by docker

### ISSUE THREAD

**Issue by Frederick-S** [Frederick-S/markote#8]
https://stackoverflow.com/questions/51287411/flask-url-for-generates-http-instead-of-https-when-running-by-docker

**Comment by Anusha2605** [comment]
Any update on this issue? Even I am facing the same issue.
Dash application loads properly with http but page does not load with https.
Docker logs of the web application tells that application is running as expected. But logs of Ngnix tells something like below:

2018/09/29 06:41:17 [error] 43#0: *4741 open() "/usr/share/nginx/html/_dash-component-suites/dash_renderer/react@15.4.2.min.js" failed (2: No such file or directory), client: 172.31.135.12, server: ~^[0-9]*, request: "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.14.1&m=1538144648 HTTP/1.1", host: "xxxx", referrer: "https://xxxx/rdh"

2018/09/29 06:41:17 [error] 43#0: *4735 open() "/usr/share/nginx/html/_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js" failed (2: No such file or directory), client: 172.31.135.12, server: ~^[0-9]*, request: "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.14.1&m=1538144648 HTTP/1.1", host: "xxxx", referrer: "https://xxxx/rdh"

**Comment by Frederick-S** [comment]
@Anusha2605 I still have no idea abount this issue.
